<?php
# CONSTANTES DE TIPO DE USUÁRIO
const TYPE_ACCOUNT_USER = 0;
const TYPE_ACCOUNT_ADMIN = 1;
const TYPE_ACCOUNT_MOD = 2;

# CONSTANTE DE STATUS DE EGRESSO
const STATUS_IN_ANALISYS='0';
const STATUS_APROVED='1';
const STATUS_REPROVED='2';
const STATUS_INACTIVE='3';